# -*- coding: utf-8 -*-
"""01_Expressions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQ6FgVCwnQA4SeTRQJOxKNimpVCtOJIS
"""

"""
Program: dicesimulator
----------------------
Simulate rolling two dice, three times. Prints
the results of each die roll. This program is used
to show how variable scope works.
"""

import random

NUM_SIDES = 6

def roll_dice():
    die1 = random.randint(1, NUM_SIDES)
    die2 = random.randint(1, NUM_SIDES)
    total = die1 + die2
    print(f"Die 1: {die1}, Die 2: {die2} → Total: {total}")

def main():
    die1 = 10
    print(f"die1 in main() starts as: {die1}")

    for _ in range(3):
        roll_dice()

    print(f"die1 in main() is still: {die1}")

if __name__ == '__main__':
    main()



"""**02_e=mc2.py**"""

C = 299792458  # Speed of light in m/s

def main():
    mass_in_kg = float(input("Enter kilos of mass: "))

    energy_in_joules = mass_in_kg * (C ** 2)

    print("e = m * C^2...")
    print(f"m = {mass_in_kg} kg")
    print(f"C = {C} m/s")
    print(f"{energy_in_joules} joules of energy!")

if __name__ == '__main__':
    main()

"""**03_foot_to_inches.py**"""

INCHES_IN_FOOT = 12  # 1 foot = 12 inches

def main():
    feet = float(input("Enter number of feet: "))
    inches = feet * INCHES_IN_FOOT
    print(f"That is {inches} inches!")

if __name__ == '__main__':
    main()

"""**04_pythagorem_theorem.py**"""

import math

def main():
    ab = float(input("\033[1m\033[3mEnter the length of AB:\033[0m "))
    ac = float(input("\033[1m\033[3mEnter the length of AC:\033[0m "))

    bc = math.sqrt(ab**2 + ac**2)

    print(f"The length of BC (the hypotenuse) is: {bc}")

if __name__ == '__main__':
    main()

"""**05_remainder_division.py**"""

def main():
    num1: int = int(input("\033[1;3mPlease enter an integer to be divided:\033[0m "))
    num2: int = int(input("\033[1;3mPlease enter an integer to divide by:\033[0m "))

    quotient: int = num1 // num2
    remainder: int = num1 % num2

    print(f"The result of this division is {quotient} with a remainder of {remainder}")

if __name__ == '__main__':
    main()

"""**06_rolldice.py**"""

import random

NUM_SIDES: int = 6

def main():


    die1: int = random.randint(1, NUM_SIDES)
    die2: int = random.randint(1, NUM_SIDES)

    total: int = die1 + die2

    print("Dice have", NUM_SIDES, "sides each.")
    print("First die:", die1)
    print("Second die:", die2)
    print("Total of two dice:", total)

if __name__ == '__main__':
    main()

"""**07_second_in_year.py**"""

# Useful constants to help make the math easier and cleaner!
DAYS_PER_YEAR: int = 365
HOURS_PER_DAY: int = 24
MIN_PER_HOUR: int = 60
SEC_PER_MIN: int = 60

def main():
    # Calculate total seconds in a year using multiplication
    total_seconds = DAYS_PER_YEAR * HOURS_PER_DAY * MIN_PER_HOUR * SEC_PER_MIN

    # Print the result in a nice formatted way
    print(f"There are {total_seconds} seconds in a year!")

# Call the main function
if __name__ == '__main__':
    main()

"""08_tiny_mad_lib.py"""

# Sentence beginning
SENTENCE_START: str = "Panaversity is fun. I learned to program and used Python to make my "

def main():
    # Get the three inputs from the user
    adjective: str = input("Please type an adjective and press enter. ")
    noun: str = input("Please type a noun and press enter. ")
    verb: str = input("Please type a verb and press enter. ")

    print(SENTENCE_START + adjective + " " + noun + " " + verb + "!")

if __name__ == '__main__':
    main()