# -*- coding: utf-8 -*-
"""02_Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isTxK5MEuw0IIrIslhp2bRyHPypInOnX

01_add_many_numbers.py
"""

def sum_of_numbers(numbers):
    total = 0
    for num in numbers:
        total += num
    return total

def main():
    numbers_list = [10, 20, 30, 40, 50]
    result = sum_of_numbers(numbers_list)
    print("List:", numbers_list)
    print("Sum of numbers:", result)

if __name__ == '__main__':
    main()

"""02_double_list.py"""

def main():

    numbers = [1, 2, 3, 4]


    for i in range(len(numbers)):
        numbers[i] *= 2


    print("Doubled List:", numbers)


if __name__ == '__main__':
    main()

"""04_flowing_with_data_structure.py"""

def add_three_copies(my_list, data):
    """ Adds three copies of data to the given list (mutable behavior). """
    my_list.append(data)
    my_list.append(data)
    my_list.append(data)

def main():
    # User input
    message = input("Enter a message to copy: ")

    # Empty list before modification
    my_list = []
    print("List before:", my_list)

    # Call the function (list changes without returning)
    add_three_copies(my_list, message)

    # List after modification
    print("List after:", my_list)

# Required line to run the program
if __name__ == '__main__':
    main()

"""05_get_first_element.py"""

def get_first_element(lst):
    """ Prints the first element of a given non-empty list. """
    print("The first element in the list is:", lst[0])

def main():

    n = int(input("Enter the number of elements in the list: "))
    lst = []

    for i in range(n):
        element = input(f"Enter element {i+1}: ")
        lst.append(element)


    get_first_element(lst)

# Required line to run the program
if __name__ == '__main__':
    main()

"""06_get_last_element.py"""

def get_first_element(lst):
    """ Prints the first element of a given non-empty list. """
    print("The Last element in the list is:", lst[-1])

def main():
    # User se list input lene ka tareeqa
    n = int(input("Enter the number of elements in the list: "))
    lst = []

    for i in range(n):
        element = input(f"Enter element {i+1}: ")
        lst.append(element)  # List me element add karna

    # Function call to print the first element
    get_first_element(lst)

# Required line to run the program
if __name__ == '__main__':
    main()

"""07_get_list.py"""

def main():
    lst = []  # Empty list to store user inputs

    while True:
        value = input("Enter a value: ")  # Taking input from user

        if value == "":  # If user presses enter without typing anything, exit loop
            break

        lst.append(value)  # Adding value to the list

    print("Here's the list:", lst)  # Printing the final list

# Required line to run the program
if __name__ == '__main__':
    main()

"""08_get_shorten.py"""

MAX_LENGTH = 3  # Define the maximum allowed length

def shorten(lst):
    while len(lst) > MAX_LENGTH:  # Jab tak list ka size MAX_LENGTH se bada hai
        removed_item = lst.pop()  # Last element remove karo
        print("Removed:", removed_item)  # Remove kiya hua item print karo

def main():
    lst = []  #

    # User se list input lena
    n = int(input("Enter number of elements in the list: "))
    for _ in range(n):
        value = input("Enter a value: ")
        lst.append(value)

    print("Original list:", lst)  # Pehli list print karo
    shorten(lst)  # shorten function ko call karo
    print("Shortened list:", lst)  # Final list print karo


if __name__ == '__main__':
    main()