# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHFflSqXfcUZlREG16Berkl3Pq8A_Viw

01_add_two_numbers.py
"""

def main() :
  print("This program adds two numbers")
num1: str = input('enter the first number:')
num1 = int(num1)

num2: str = input('enter the second number:')
num2 = int(num2)
total_sum =num1 + num2
print(f"the total sum of {num1} and {num2} is {total_sum}")
if  __name__ == '__main__':
  main()

"""02_agreement_bot.md"""

def main():
    favorite_animal = "cat"
    print(f"My favorite animal is {favorite_animal}!")

# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()

"""02_agreement_bot.py"""

def main():
    try:
        degrees_fahrenheit = float(input("Enter temperature in Fahrenheit: ").strip().replace("F", ""))
        degrees_celsius = (degrees_fahrenheit - 32) * 5.0 / 9.0
        print(f"Temperature: {degrees_fahrenheit}F = {degrees_celsius}C")
    except ValueError:
        print("Invalid input! Please enter a valid number for temperature.")

# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()

"""04_how_old_are_they.***py***"""

def main():
    anton : int = 21  # Anton's age is given as 21 years old
    beth : int = 6 + anton  # Beth is 6 years older than Anton, so add 6 to Anton's age to get Beth's
    chen : int = 20 + beth  # Chen is 20 years older than Beth, so add 20 to Beth's age to get Chen's
    drew  : int= chen + anton  # Drew is as old as Chen's age plus Anton's age, so add them together
    ethan : int = chen  # Ethan is the same age as Chen, so set Ethan's age equal to Chen's

   # Printing the names and ages in the required format
    print(f"Anton is {anton}")
    print(f"Beth is {beth}")
    print(f"Chen is  {chen}")
    print(f"Drew is {drew}")
    print(f"Ethan is {ethan}")

if __name__ == '__main__':
    main()

"""05_triangle_perimetre.py"""

def main():

# Prompt the user to enter the lengths of each side of the triangle
    side1 = float(input("What is the length of side 1? "))
    side2 = float(input("What is the length of side 2? "))
    side3 = float(input("What is the length of side 3? "))

    # Calculate the perimeter by summing the lengths of the sides
    perimeter = side1 + side2 + side3

    # Print the perimeter of the triangle
    print(f"The perimeter of the triangle is {perimeter}")


if __name__ == '__main__':
    main()

"""06_square_number.***py***"""

def main():
    number = 10  # You can change this number to any integer you want to square
    square = number ** 2
    print(f"The number squared is {square}")

if __name__ == "__main__":
    main()